'use client';

import React, { useRef, useEffect } from 'react';


const safetyPoints = [
  {
    icon: '🩺',
    title: 'Not a medical or nutritional advisor',
    desc: 'Chef Pepe does not replace professional medical, nutritional, or allergy advice. Always consult a qualified professional for health-related decisions.',
  },
  {
    icon: '🌡️',
    title: 'Verify cooking temperatures',
    desc: 'Always confirm internal temperatures with a food thermometer. Safe cooking temperatures vary by food type and should be verified independently.',
  },
  {
    icon: '⚠️',
    title: 'Check allergens carefully',
    desc: 'Ingredient identification may not be exact. Always verify allergens, cross-contamination risks, and dietary restrictions before cooking or serving.',
  },
  {
    icon: '🔍',
    title: 'Confirm before you start',
    desc: 'Image analysis results should be reviewed and confirmed by the user before any cooking instructions begin.',
  },
];

export default function ChefPepeSafety() {
  const sectionRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) entry.target.classList.add('animate-in-view');
        });
      },
      { threshold: 0.1 }
    );
    const elements = sectionRef?.current?.querySelectorAll('.scroll-reveal');
    elements?.forEach((el) => observer?.observe(el));
    return () => observer?.disconnect();
  }, []);

  return (
    <section ref={sectionRef} className="bg-secondary py-16 lg:py-20" aria-labelledby="safety-heading">
      <div className="max-w-5xl mx-auto px-6 lg:px-8">
        <div className="scroll-reveal text-center mb-12">
          <div className="w-14 h-14 bg-accent/10 rounded-2xl flex items-center justify-center text-2xl mx-auto mb-4">
            🛡️
          </div>
          <h2 id="safety-heading" className="text-hero-md font-extrabold text-foreground mb-4">
            Helpful guidance, human responsibility.
          </h2>
          <p className="text-muted-foreground text-base max-w-xl mx-auto leading-relaxed">
            Chef Pepe does not replace professional medical, nutritional, allergy, or food-safety advice. Always verify ingredients, allergens, storage, temperatures, and doneness.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 scroll-reveal">
          {safetyPoints?.map((point, i) => (
            <div
              key={point?.title}
              className="bg-card border border-border rounded-2xl p-6 flex gap-4 items-start"
              style={{ animationDelay: `${i * 0.1}s` }}
            >
              <div className="w-10 h-10 bg-accent/10 rounded-xl flex items-center justify-center text-xl shrink-0">
                {point?.icon}
              </div>
              <div>
                <h3 className="font-bold text-foreground text-sm mb-1">{point?.title}</h3>
                <p className="text-muted-foreground text-xs leading-relaxed">{point?.desc}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-8 p-5 bg-card border-l-4 border-accent rounded-2xl scroll-reveal">
          <p className="text-foreground text-sm leading-relaxed">
            <strong>AI Disclosure:</strong> Chef Pepe is an AI assistant. His responses are generated by machine learning models and may contain errors or omissions. Chew Network is not liable for outcomes resulting from following Chef Pepe's guidance. Always apply your own judgment and verify critical information independently.
          </p>
        </div>
      </div>
    </section>
  );
}